Traceback (most recent call last):
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Apply monte carlo to see how uncertainty affects the velocity 

#uncertainty 
d_err = 1
t_err = 0.1 

#number of simulations
N = 10000 

#loc is mean, scale is st deviation
#here we pick a mean of zero for the noise so that when the "error" is added to our constants
#the average value of the parameter does not change
#we pick the standard deviation to be equal to the size of the error, so that we can "add"
#in the variation in the parameter's value due to the uncertainty
d_mc = d + np.random.normal(loc=0.0, scale=d_err,size=N)
t_mc = t + np.random.normal(loc=0.0, scale=t_err,size=N)

v_mc = d_mc/t_mc
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 15[0m
[1;32m      8[0m N [38;5;241m=[39m [38;5;241m10000[39m 
[1;32m     10[0m [38;5;66;03m#loc is mean, scale is st deviation[39;00m
[1;32m     11[0m [38;5;66;03m#here we pick a mean of zero for the noise so that when the "error" is added to our constants[39;00m
[1;32m     12[0m [38;5;66;03m#the average value of the parameter does not change[39;00m
[1;32m     13[0m [38;5;66;03m#we pick the standard deviation to be equal to the size of the error, so that we can "add"[39;00m
[1;32m     14[0m [38;5;66;03m#in the variation in the parameter's value due to the uncertainty[39;00m
[0;32m---> 15[0m d_mc [38;5;241m=[39m d [38;5;241m+[39m [43mnp[49m[38;5;241m.[39mrandom[38;5;241m.[39mnormal(loc[38;5;241m=[39m[38;5;241m0.0[39m, scale[38;5;241m=[39md_err,size[38;5;241m=[39mN)
[1;32m     16[0m t_mc [38;5;241m=[39m t [38;5;241m+[39m np[38;5;241m.[39mrandom[38;5;241m.[39mnormal(loc[38;5;241m=[39m[38;5;241m0.0[39m, scale[38;5;241m=[39mt_err,size[38;5;241m=[39mN)
[1;32m     18[0m v_mc [38;5;241m=[39m d_mc[38;5;241m/[39mt_mc

[0;31mNameError[0m: name 'np' is not defined

